/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WebgumContractAbi } from "./WebgumContractAbi";

export { WebgumContractAbi__factory } from "./factories/WebgumContractAbi__factory";
