import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../src/components/header';
import HeroSection from '../src/components/herosection';
import styles from '../styles/Home.module.css';
import Categories from '../src/components/categories';
import Link from 'next/link';
import SearchBar from '../src/components/searchbar';
import HowItWorks from '../src/components/how-it-works/HowItWorks';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>webgum</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />
        <HeroSection />
        <SearchBar />
        <div style={{textAlign: "center", fontSize: "2rem", cursor: "pointer", marginTop: "40px"}}>
          <Link href="/projects">See the Latest Projects</Link>
        </div>
        <Categories />
        <HowItWorks />
      </main>
    </div>
  );
};

export default Home;
