import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/components/header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>WebGum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
      </main>
    </div>
  )
}

export default Home
