import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/components/header'
import HeroSection from '../src/components/herosection'
import categories from "../src/components/categories";
import styles from '../styles/Home.module.css'
import Categories from '../src/components/categories';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>WebGum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <HeroSection />
        <Categories/>
      </main>
    </div>
  )
}

export default Home
